CREATE DATABASE IF NOT EXISTS comercial_link CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'comercial'@'%' IDENTIFIED BY 'CAMBIA_ESTA_CLAVE';
GRANT ALL PRIVILEGES ON comercial_link.* TO 'comercial'@'%';
FLUSH PRIVILEGES;
